version: '3.9'

# Importar dados
# mongoimport --uri=mongodb://root:toor@127.0.0.1:27017 --authenticationDatabase=admin --db=steam --collection=games --type=csv --headerline --file=game_database.csv

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    network_mode: host
    ports:
      - "27017:27017"
  
  gatling:
    image: denvazh/gatling:latest
    container_name: gatling
    network_mode: host
    volumes:
      - ./gatling/user-files:/opt/gatling/user-files
      - ./gatling/results:/opt/gatling/results
    entrypoint: /bin/bash
    command: [ "-c", "tail -f /dev/null" ]

  app1: 
    build: ./nest-project
    container_name: app1
    working_dir: /nest
    network_mode: host
    environment: 
      HTTP_PORT: 3000
    depends_on:
      - mongo

  app2: 
    build: ./nest-project
    container_name: app2
    working_dir: /nest
    network_mode: host
    environment: 
      HTTP_PORT: 3001
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    network_mode: host